inherit_gem:
  dlss_cops: "config/dlss_baseline.yml"

AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'

Rails:
  Enabled: true

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'

Metrics/LineLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'