# Turn on RSpec cops
require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.2
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - '.internal_test_app/**/*'
    - 'spec/fixtures/**/*'
    - 'spec/internal/**/*'
    - 'spec/test_app_templates/**/*'
    - 'Rakefile'
    - 'lib/tasks/rubocop.rake'

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'app/controllers/catalog_controller.rb'

Style/IndentationConsistency:
  EnforcedStyle: rails

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/WordArray:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'

Rails/HasAndBelongsToMany:
  Exclude:
    - 'app/models/role.rb'

RSpec/AnyInstance:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/**/*'
    - 'spec/views/**/*'

RSpec/FilePath:
  Exclude:
    - 'spec/routing/**/*'
