notifications:
  email: false

rvm:
  - 2.3.0

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false
language: ruby
cache: bundler

jdk:
  - oraclejdk8

before_script:
  - bundle exec rake db:create

services:
  - postgresql
  - redis-server
