notifications:
  email: false

rvm:
  - 2.3.0

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false
language: ruby
cache: bundler

jdk:
  - oraclejdk8

before_script:
  - bundle exec rake db:create

before_deploy:
  - mkdir build; zip -q -r build/hybox.zip .

services:
  - postgresql
  - redis-server

deploy:
  provider: s3
  access_key_id: ***REMOVED***
  secret_access_key:
    secure: aeuGLdENwlyuJGHDKzBbv4VRAd76BrIzQ7fZswiKPimBdmQ6nsEeHqrtv/TgATfyxAFRJ5IiKCnpFfx4AItD3SofflfiVkFOLL03ZSHkkNf3IZV4q1QDdnzyjGXbBlP2PSNWHujyfFpoAZv8W3mniKqMVYMifkdNdleBucqMS3YVWik5wzfU2ahLgRDQpp6mWI1lHwbSktJkkhCNbJqRxp63cREYnSZsjckavcsAWQk8Z2Dw9KoEMxiI6MAypRkHD2RBeY4AJZoYtRlZV4zNQL78vq8JT5WBTp7VedeXSBYhdDxjbtA3G/zYhvetzW6crKKmQgCvnhcWiHn+KBM6Q3yZc07TtOYqBmyBMS7WaFtAlV0tWCh9zKrx4bYfUBNurkZYc7hSiKVDbnaEpNJdKUE8mnF2r2y9esTcaBYiE31jp/T/hTKSfsz+vf39axm3FGMumziBs5luArD4+j3AJgn9SgpyTa+uF38pq6E5OsvkEAE0+hrHKGVjIKaFWGh637qw4OIeVU6C0WAJYGnmkVmllxLRdKUB3fLICuPytDLkSKhDzEBgC5rXfov/qupFN8eFFiX1kWpRJCocyVUJYU2lUNuOUzX5eeGUuXZgTKU1X20rOycCd4ft3CuxLLbEDT+xyjeJ2lSCEPknRkmyANtH0mycyBVaYtCzuVm0MMA=
  bucket: hybox-deployment-artifacts
  region: us-east-1
  local_dir: build
  skip_cleanup: true
