multitenant: false

solr:
  url: http://127.0.0.1:8983/solr/
  configset: hybox
  configset_source_path: <%= File.join(Rails.root, 'solr', 'config') %>
  collection_options:
    collection.configName: hybox
    numShards: 1

zookeeper:
  connection_str: 'localhost:9983/configs'
