multitenancy:
  enabled: false
  default_host: "<%= ENV.fetch('SETTINGS__MULTITENANCY__DEFAULT_HOST', '%{tenant}.dev') %>"
  host: "<%= ENV.fetch('SETTINGS__MULTITENANCY__HOST', 'localhost') %>"

redis:
  default_namespace: hybox

solr:
  url: "<%= ENV.fetch('SETTINGS__SOLR__URL', 'http://127.0.0.1:8983/solr/') %>"
  configset: hybox
  configset_source_path: <%= File.join(Rails.root, 'solr', 'config') %>
  collection_options:
    collection.configName: hybox
    numShards: 1

zookeeper:
  connection_str: "<%= ENV.fetch('SETTINGS__ZOOKEEPER__CONNECTION_STR', 'localhost:9983/configs') %>"

active_job_queue:
  url: <%= ENV['SETTINGS__ACTIVE_JOB_QUEUE__URL'] %>

s3:
  upload_bucket: <%= ENV['SETTINGS__S3__UPLOAD_BUCKET'] %>
