multitenancy:
  enabled: false
  default_host: "<%= ENV.fetch('SETTINGS__MULTITENANCY__DEFAULT_HOST', '%{tenant}.dev') %>"

solr:
  url: "<%= ENV.fetch('SETTINGS__SOLR__URL', 'http://127.0.0.1:8983/solr/') %>"
  configset: hybox
  configset_source_path: <%= File.join(Rails.root, 'solr', 'config') %>
  collection_options:
    collection.configName: hybox
    numShards: 1

zookeeper:
  connection_str: "<%= ENV.fetch('SETTINGS__ZOOKEEPER__CONNECTION_STR', 'localhost:9983/configs') %>"