# These settings can also be provided as environment variables, in the form, e.g.:
#    SETTING__ACTIVE_JOB_QUEUE__URL=http://...
#
# The mapping is described in `./config/initializers/config.rb`.
#
multitenancy:
  enabled: false
  default_host: "%{tenant}.dev"
  host: localhost

redis:
  default_namespace: hybox

solr:
  url: "http://127.0.0.1:8983/solr/"
  configset: hybox
  configset_source_path: <%= File.join(Rails.root, 'solr', 'config') %>
  collection_options:
    collection.configName: hybox
    numShards: 1

zookeeper:
  connection_str: "localhost:9983/configs"

active_job_queue:
  url:

s3:
  upload_bucket:

fits_path: "fits.sh"

# Is this application a worker? (processing queues, not a webapp)
worker: false
