replicaCount: 2

resources:
  limits:
    memory: "4Gi"
    cpu: "500m"
  requests:
    memory: "2Gi"
    cpu: "250m"

livenessProbe:
  enabled: true
  exec:
    command:
      - sh
      - -c
      - /health/ping_liveness_local.sh 5
  initialDelaySeconds: 60       # wait longer before first check
  periodSeconds: 60             # check every 60s
  timeoutSeconds: 10            # allow 10s to respond
  successThreshold: 1
  failureThreshold: 5           # 5 failures = ~5 mins grace

readinessProbe:
  enabled: true
  exec:
    command:
      - sh
      - -c
      - /health/ping_readiness_local.sh 5
  initialDelaySeconds: 30     # start earlier than liveness
  periodSeconds: 60           # check every 60s
  timeoutSeconds: 10          # allow up to 10s per check
  successThreshold: 1
  failureThreshold: 5         # allow 5 failures before marking unready

brandingVolume:
  storageClass: efs-sc
derivativesVolume:
  storageClass: efs-sc
uploadsVolume:
  storageClass: efs-sc

extraVolumeMounts: &volMounts
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/tmp/imports
    subPath: imports
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/tmp/exports
    subPath: exports
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/public/system
    subPath: public-system
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/public/uploads
    subPath: public-uploads
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/tmp/network_files
    subPath: network-files

ingress:
  enabled: true
  hosts:
    - host: utk-hyku-production.notch8.cloud
      paths:
        - path: /
    - host: "*.utk-hyku-production.notch8.cloud"
      paths:
        - path: /
  annotations: {
    kubernetes.io/ingress.class: "nginx",
    nginx.ingress.kubernetes.io/proxy-body-size: "0",
    cert-manager.io/cluster-issuer: letsencrypt-production-dns
    }
  tls:
    - hosts:
        - utk-hyku-production.notch8.cloud
        - "*.utk-hyku-production.notch8.cloud"
      secretName: notch8cloud

extraEnvVars: &envVars
  - name: AWS_ACCESS_KEY_ID
    value: $AWS_ACCESS_KEY_ID
  - name: AWS_BUCKET
    value: "besties-fcrepo"
  - name: AWS_REGION
    value: 'us-west-2'
  - name: AWS_SECRET_ACCESS_KEY
    value: $AWS_SECRET_ACCESS_KEY
  - name: CONFDIR
    value: "/app/samvera/hyrax-webapp/solr/conf"
  - name: DB_ADAPTER
    value: postgresql
  - name: DB_HOST
    value: postgres-cluster-alpha-primary.postgres.svc.cluster.local
  - name: DB_NAME
    value: utk-hyku-production-hyrax
  - name: DB_PASSWORD
    value: $DB_PASSWORD
  - name: DB_USER
    value: main
  - name: EXTERNAL_IIIF_URL
    value: https://wtchtwt5fcxnxj5guruoadqpwm0uvgjl.lambda-url.us-west-2.on.aws/iiif/2
  - name: FCREPO_BASE_PATH
    value: /utk-hyku
  - name: FCREPO_HOST
    value: fcrepo.utk-hyku-production.svc.cluster.local:8080
  - name: FCREPO_PATH
    value: /rest
  - name: FCREPO_URL
    value: http://fcrepo.utk-hyku-production.svc.cluster.local:8080/rest
  - name: GOOD_JOB_CLEANUP_DISCARDED_JOBS
    value: "false"
  - name: GOOD_JOB_CLEANUP_INTERVAL_SECONDS
    value: "86400"
  - name: GOOD_JOB_CLEANUP_PRESERVED_JOBS_BEFORE_SECONDS_AGO
    value: "604800"
  - name: GOOD_JOB_MAX_THREADS
    value: "5"
  - name: HYKU_ACTIVE_JOB_QUEUE_URL
    value: good_job
  - name: HYKU_ADMIN_HOST
    value: hykuadmin.lib.utk.edu
  - name: HYKU_ADMIN_ONLY_TENANT_CREATION
    value: "false"
  - name: HYKU_BULKRAX_ENABLED
    value: "true"
  - name: HYKU_CONTACT_EMAIL
    value: ut_LibDI_Admin@utk.edu
  - name: HYKU_DEFAULT_HOST
    value: "%{tenant}.lib.utk.edu"
  - name: HYKU_ENABLED
    value: "true"
  - name: HYKU_FILE_ACL
    value: "true"
  - name: HYKU_MULTITENANT
    value: "true"
  - name: HYKU_ROOT_HOST
    value: lib.utk.edu
  - name: HYKU_SSL_CONFIGURED
    value: "true"
  - name: HYRAX_ACTIVE_JOB_QUEUE
    value: good_job
  - name: HYRAX_FITS_PATH
    value: /app/fits/fits.sh
  - name: HYRAX_USE_SOLR_GRAPH_NESTING
    value: "true"
  - name: IN_DOCKER
    value: "true"
  - name: LD_LIBRARY_PATH
    value: /app/fits/tools/mediainfo/linux
  - name: PASSENGER_APP_ENV
    value: production
  - name: RAILS_CACHE_STORE_URL
    value: redis://:$REDIS_PASSWORD@utk-hyku-production-redis-master:6379/0
  - name: RAILS_ENV
    value: production
  - name: RAILS_LOG_TO_STDOUT
    value: "true"
  - name: RAILS_MAX_THREADS
    value: "5"
  - name: RAILS_SERVE_STATIC_FILES
    value: "true"
  - name: REDIS_HOST
    value: utk-hyku-production-redis-master
  - name: REDIS_URL
    value: redis://:$REDIS_PASSWORD@utk-hyku-production-redis-master:6379/0
  - name: ROB_EMAIL
    value: rob@notch8.com
  - name: ROB_PASSWORD
    value: testing123
  - name: S3_DOWNLOADS
    value: "true"
  - name: SENTRY_DSN
    value: $SENTRY_DSN
  - name: SENTRY_ENVIRONMENT
    value: "utk-hyku-production"
  - name: SMTP_ADDRESS
    value: smtp.sendgrid.net
  - name: SMTP_DOMAIN
    value: live.utk.edu
  - name: SMTP_ENABLED
    value: "true"
  - name: SMTP_PASSWORD
    value: $SMTP_PASSWORD
  - name: SMTP_PORT
    value: "587"
  - name: SMTP_TYPE
    value: plain
  - name: SMTP_USER_NAME
    value: apikey
  - name: SOLR_ADMIN_PASSWORD
    value: $SOLR_ADMIN_PASSWORD
  - name: SOLR_ADMIN_USER
    value: admin
  - name: SOLR_COLLECTION_NAME
    value: utk-hyku
  - name: SOLR_CONFIGSET_NAME
    value: utk-hyku
  - name: SOLR_HOST
    value: solr-headless.solr
  - name: SOLR_PORT
    value: "8983"
  - name: SOLR_URL
    value: http://admin:$SOLR_ADMIN_PASSWORD@solr-headless.solr:8983/solr/
  - name: SUPPORT_EMAIL
    value: support@notch8.com
  - name: SUPPORT_PASSWORD
    value: testing123
  - name: TEST_USER_EMAIL
    value: user@notch8.com
  - name: TEST_USER_PASSWORD
    value: testing123

worker:
  replicaCount: 3
  resources:
    limits:
      memory: "6Gi"
      cpu: "3"
    requests:
      memory: "3Gi"
      cpu: "1"
  podSecurityContext:
    runAsUser: 1001
    runAsGroup: 101
    fsGroup: 101
    fsGroupChangePolicy: "OnRootMismatch"
  extraVolumeMounts: *volMounts
  extraEnvVars: *envVars

podSecurityContext:
  runAsUser: 1001
  runAsGroup: 101
  fsGroup: 101
  fsGroupChangePolicy: "OnRootMismatch"

embargoRelease:
  enabled: false
leaseRelease:
  enabled: false

imagePullSecrets:
  - name: github

fcrepo:
  resources:
    limits:
      memory: "4Gi"
      cpu: "2"
    requests:
      memory: "2Gi"
      cpu: "1"
  enabled: false
postgresql:
  enabled: false
redis:
  cluster:
    enabled: false
  password: $REDIS_PASSWORD
solr:
  enabled: false

externalFcrepoHost: fcrepo.utk-hyku-production.svc.cluster.local
externalPostgresql:
  host: postgres-cluster-alpha-primary.postgres.svc.cluster.local
  username: main
  password: $DB_PASSWORD
  database: utk-hyku-production-hyrax

externalSolrPassword: $SOLR_ADMIN_PASSWORD
externalSolrHost: solr.solr.svc.cluster.local
externalSolrUser: admin
externalSolrCollection: "utk-hyku"


extraDeploy:
  - |-
      apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        namespace: utk-hyku-production
        name: deployment-manager
      rules:
      - apiGroups: ["apps"]
        resources: ["deployments"]
        verbs: ["get", "list", "watch", "update", "patch"]
      ---
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: hyrax-deployment-manager-binding
        namespace: default
      subjects:
      - kind: ServiceAccount
        name: utk-hyku-production-hyrax
        namespace: utk-hyku-production
      roleRef:
        kind: Role
        name: deployment-manager
        apiGroup: rbac.authorization.k8s.io
