name: "Build Test Lint"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: scientist-softserv/actions/.github/workflows/build.yaml@main
  test:
    needs: build
    uses: scientist-softserv/actions/.github/workflows/test.yaml@main
  lint:
    needs: build
    uses: scientist-softserv/actions/.github/workflows/lint.yaml@main
