name: "Build Test Lint"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call-workflow:
    runs-on: [self-hosted, linux, ARM64]
    uses: scientist-softserv/build-lint-test-action/.github/workflows/build-test-lint.yaml@main
