name: "Build Test Lint"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: scientist-softserv/actions/.github/workflows/build.yaml@main
    with:
      target: hyku-base
  build-worker:
    needs: build
    uses: scientist-softserv/actions/.github/workflows/build-worker.yaml@main
    with:
      target: hyku-worker
  test:
    needs: build
    uses: scientist-softserv/actions/.github/workflows/test.yaml@main
  lint:
    needs: build
    uses: scientist-softserv/actions/.github/workflows/lint.yaml@main
