name: "Deploy"
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy to Environment'
        require: true
        default: 'staging'
        type: choice
        options:
          - staging
          - demo
          - production
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  call-workflow:
    uses: scientist-softserv/deploy-action/.github/workflows/deploy.yaml@flexible-names
    with:
      k8s-release-name: fake
      k8s-namespace: ${{ format('{0}-{1}', inputs.environment, github.event.repository.name) }}
    secrets: inherit
