name: "Deploy Staging"
on:
  workflow_dispatch: {}

env:
  REGISTRY: ghcr.io

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    container: dtzar/helm-kubectl:3.9.4
    env:
      DEPLOY_IMAGE: ghcr.io/${{ github.repository }}
      WORKER_IMAGE: ghcr.io/${{ github.repository }}/worker
      HELM_EXPERIMENTAL_OCI: 1
      HELM_RELEASE_NAME: utk-hyku-staging
      KUBE_NAMESPACE: utk-hyku-staging
      HELM_EXTRA_ARGS: >
        --values ops/staging-deploy.yaml
      KUBECONFIG_FILE: ${{ secrets.STAGING_KUBECONFIG_FILE }}
      KUBECONFIG: ./kubeconfig.yml
      STAGING_SOLR_ADMIN_PASSWORD: ${{ secrets.STAGING_SOLR_ADMIN_PASSWORD }}
      STAGING_DB_PASSWORD: ${{ secrets.STAGING_DB_PASSWORD }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
    steps:
      - name: Set env
        run: >-
          echo "TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV;
          echo "DEPLOY_TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV;
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Do deploy
        run: >-
          echo $KUBECONFIG_FILE | base64 -d > $KUBECONFIG;
          DOLLAR=$ envsubst < ops/staging-deploy.tmpl.yaml > ops/staging-deploy.yaml;
          cat ops/staging-deploy.yaml;
          ./bin/helm_deploy utk-staging utk-staging
