# TODO build x for multiple images
# TODO parallelize rubocop and rspec
# TODO helm deployment

name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: echo "TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Github Container Login
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull from cache to speed up build
        run: TAG=main docker-compose pull web || true
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          target: hyku-base
          build-args: |
            HYKU_BULKRAX_ENABLED=true
            EXTRA_APK_PACKAGES=less vim bash openjdk11-jre ffmpeg rsync
          cache_from: |
            ghcr.io/notch8/utk-hyku:main
            ghcr.io/notch8/utk-hyku:${TAG}
          push: true
          tags: |
            ghcr.io/notch8/utk-hyku:${TAG}
      - name: Build and push worker
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          target: hyku-worker
          build-args: |
            HYKU_BULKRAX_ENABLED=true
            EXTRA_APK_PACKAGES=less vim bash openjdk11-jre ffmpeg rsync
          cache_from: |
            ghcr.io/notch8/utk-hyku:main
            ghcr.io/notch8/utk-hyku:${TAG}
          push: true
          tags: |
            ghcr.io/notch8/utk-hyku/worker:${TAG}

      # - name: Build web
      #   run: docker-compose build web
      # - name: Build Worker
      #   run: docker-compose build worker
      # - name: Push to registry
      #   run: >-
      #     docker-compose push web;
      #     docker-compose push worker
      # - name: Update main tag
      #   if: github.ref == 'refs/heads/main'
      #   run: >-
      #     docker tag ghcr.io/notch8/utk-hyku:${GITHUB_SHA::8} ghcr.io/notch8/utk-hyku:main;
      #     docker tag ghcr.io/notch8/utk-hyku/worker:${GITHUB_SHA::8} ghcr.io/notch8/utk-hyku/worker:main;
      #     TAG=main docker-compose push web;
      #     TAG=main docker-compose push worker

  lint:
    # needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        # run: echo "TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV
        run: echo "TAG=f9867d90" >> $GITHUB_ENV
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Github Container Login
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull from cache to speed up build
        run: >-
          docker-compose pull web;
          docker-compose pull worker
      - name: Run Rubocop
        run: docker-compose run web bundle exec rubocop --parallel --format junit --out rubocop.xml
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: 'rubocop*.xml'

  test:
    # needs: build
    runs-on: ubuntu-latest
    env:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      CONFDIR: "/app/samvera/hyrax-webapp/solr/config"
      DB_CLEANER_ALLOW_REMOTE_DB_URL: "true"
    steps:
      - name: Set env
        # run: echo "TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV
        run: echo "TAG=f9867d90" >> $GITHUB_ENV
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Github Container Login
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull from cache to speed up build
        run: >-
          docker-compose pull web;
          docker-compose pull worker
      - name: Start containers
        run: docker-compose up -d web
      - name: Setup solr
        run: >-
          docker-compose exec -T web bash -c
          "solrcloud-upload-configset.sh /app/samvera/hyrax-webapp/solr/config &&
          SOLR_COLLECTION_NAME=hydra-test solrcloud-assign-configset.sh &&
          solrcloud-assign-configset.sh"
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        with:
          limit-access-to-actor: true
      - name: Run Specs
        run: docker-compose exec -T web bundle exec rspec --format progress --tag ~speed:slow --format RspecJunitFormatter --out rspec.xml
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: 'rspec*.xml'
