name: "GitGuardian Scan"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  scan:
    uses: scientist-softserv/actions/.github/workflows/gitguardian.yaml@self-hosted-runner